export function createEmptyActivity(id = '') {
  return {
    id,
    title: '',
    organizer: '',
    organizerAvatar: '/static/userImg/user.png',
    creatorId: '',
    creator_id: '',
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&q=80&w=900',
    category: '',
    date: '',
    dateValue: '',
    dayOfWeek: '',
    time: '',
    endTime: '',
    location: '',
    address: '',
    latitude: '',
    longitude: '',
    distance: '',
    participantCount: 0,
    maxParticipants: 0,
    hasParticipantLimit: false,
    partyMode: 'free',
    price: '0',
    amount: 0,
    requireApproval: false,
    isCreator: false,
    status: 'recruiting',
    lifecycleStatus: 'recruiting',
    applicationStatus: 'not_applied',
    viewCount: 0,
    likeCount: 0,
    description: '',
    questions: [],
    tags: [],
    moderationStatus: 'visible',
    moderationNote: ''
  }
}
